### ISSUE TITLE
What is 'include higher freqs'?

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [thepirat000/spleeter-api#4]
Hey! Thank you for the interface to the spleeter. Can you give me some info on the options? I don't know what is the default for the freqs - I've never used it in console version.

**Comment by thepirat000** [comment]
It's a flag to include (or not) an average of the high frequencies on the output, since by default frequencies above 11khz are discarded. 

Check this out: https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-

Currently implemented by changing the "mask_extension" value to "average" on an alternate config file, here: https://github.com/thepirat000/spleeter-api/blob/97e54b4a9ba042025b063a147814ccfe6b56ec95/alt-config/2stems/base_config_hf.json#L14
